# Generated by Django 2.0 on 2018-05-04 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(default='Content'),
        ),
        migrations.AlterField(
            model_name='post',
            name='post_title',
            field=models.CharField(default='Post Title', max_length=500),
        ),
        migrations.AlterField(
            model_name='post',
            name='visit_counter',
            field=models.IntegerField(default=0),
        ),
    ]
