# Generated by Django 2.0 on 2018-05-06 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0002_auto_20180504_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('EC', 'economy'), ('WRLD', 'world'), ('MRKT', 'market')], default='world', max_length=7),
        ),
    ]
